version: 2

jobs:
  build:
    docker:
      - image: golang:latest
        environment:
          REVIEWDOG_VERSION: "0.9.11"
    working_directory: /go/src/github.com/astronoka/migu
    steps:
      - checkout
      - run:
          name: System information
          command: 'echo "Golang $(go version)"'
      - run: 'go get -u github.com/golang/dep/cmd/dep'
      - run: 'dep ensure -v -vendor-only=true'
      - run: 'curl -fSL https://github.com/haya14busa/reviewdog/releases/download/$REVIEWDOG_VERSION/reviewdog_linux_amd64 -o reviewdog && chmod +x ./reviewdog'
      - run: 'go get honnef.co/go/tools/cmd/unused'
      - run: 'unused ./... || true | ./reviewdog -efm="%f:%l:%c: %m" -name=unused -reporter=github-pr-check'
